basePath: /api/v1
definitions:
  person-enrichment-service_server_entity.CreatePersonRequest:
    properties:
      name:
        type: string
      surname:
        type: string
    required:
    - name
    - surname
    type: object
  person-enrichment-service_server_entity.PersonResponse:
    properties:
      age:
        type: integer
      created_at:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      nationality:
        type: string
      surname:
        type: string
      updated_at:
        type: string
    type: object
  person-enrichment-service_server_entity.UpdatePersonRequest:
    properties:
      age:
        type: integer
      gender:
        type: string
      name:
        type: string
      nationality:
        type: string
      surname:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a service for enriching person data with age, gender, and nationality
  title: Person Enrichment API
  version: "1.0"
paths:
  /persons:
    get:
      consumes:
      - application/json
      description: Get people with filtering and pagination
      parameters:
      - description: Name filter
        in: query
        name: name
        type: string
      - description: Surname filter
        in: query
        name: surname
        type: string
      - description: Patronymic filter
        in: query
        name: patronymic
        type: string
      - description: Age filter
        in: query
        name: age
        type: integer
      - description: Gender filter
        in: query
        name: gender
        type: string
      - description: Nationality filter
        in: query
        name: nationality
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"data": [], "total": 0}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get people with filtering and pagination
      tags:
      - persons
    post:
      consumes:
      - application/json
      description: Create a new person with the input payload
      parameters:
      - description: Create person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/person-enrichment-service_server_entity.CreatePersonRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/person-enrichment-service_server_entity.PersonResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new person
      tags:
      - persons
  /persons/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a person
      tags:
      - persons
    get:
      consumes:
      - application/json
      description: Get a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/person-enrichment-service_server_entity.PersonResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a person by ID
      tags:
      - persons
    put:
      consumes:
      - application/json
      description: Update a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/person-enrichment-service_server_entity.UpdatePersonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/person-enrichment-service_server_entity.PersonResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a person
      tags:
      - persons
swagger: "2.0"
